server:
  port: 84

spring:
  application:
    name: cloudalibaba-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #配置nacos地址
    sentinel:
      transport:
        #认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
        dashboard: localhost:8080 #配置sentinel地址


management:
  endpoints:
    web:
      exposure:
        include: '*'